spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
logging:
  config: classpath:log4j2.xml
debug: false
file:
  templateLocation: classpath:/templates/
  staticLocation: classpath:/static/
  resourceUri: /fileUpload/**
  resourceLocation: D:/fileUpload/
  excelPath: D:/fileUpload/excel
mybatis:
  mapper-locations: classpath:mybatis/*.xml
---
# debug
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    jdbc-url: jdbc:mysql://192.168.0.53:3306/illegal_parking?serverTimezone=Asia/Seoul
    username: root
    password: tera

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 300m
---
# home
spring:
  config:
    activate:
      on-profile: home
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/illegal_parking?serverTimezone=Asia/Seoul
    username:
    password:
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 300m
---
# release
spring:
  config:
    activate:
      on-profile: release
  jpa:
    database-platform: ??
  datasource:
    url: jdbc:mysql://localhost:3306/_____?serverTimezone=Asia/Seoul
    username:
    password:
server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 30m