spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
logging:
  config: classpath:log4j2.xml
debug: false
file:
  templateLocation: classpath:/templates/
  staticLocation: classpath:/static/
  resourceUri: /fileUpload/**
  resourceLocation: D:/fileUpload/
---
# debug
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    database-platform: ??
  datasource:
    url: jdbc:mysql://localhost:3306/_____?serverTimezone=Asia/Seoul
    username: 
    password: 
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 300m
---
# release
spring:
  config:
    activate:
      on-profile: release
  jpa:
    database-platform: ??
  datasource:
    url: jdbc:mysql://localhost:3306/_____?serverTimezone=Asia/Seoul
    username: 
    password: 
server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 30m